# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

## Themes: https://hexo.io/themes/
theme: anisina  #next

# Site
title: Guanghui
subtitle:
description: A very lame cool person #A goal is not always meant to be reached, it often serves simply as something to aim at
author: Guanghui Wang
language: en #zh-Hans
timezone:

# custom Site settings
# more detail check out docs
SEOTitle: Guanghui's blog
header-img: #http://www.wikiexclusive.com/phsychology-and-relationship/images/girl.jpg
email: wghglory89@gmail.com
keyword: # seo key words

favicon: /favicon.ico # your favicon png
# custom end

# SNS settings
# RSS:
#weibo_username: wghglory89
#zhihu_username: wghglory
github_username: wghglory
#twitter_username: ehazon
facebook_username: wghglory
linkedin_username: guanghuiwang

# Review
disqus_shortname: guanghuiwang
disqus_username: guanghuiwang
#duoshuo_shortname: guanghuiwang   # theme-next
#duoshuo_username: guanghuiwang  # anisina
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing

# Build settings
anchorjs: false                        # if you want to customize anchor. check out line:181 of `post.html`

# Analytics settings
# Baidu Analytics
ba_track_id:
# Google Analytics
ga_track_id: UA-91771069-1            # Format: UA-xxxxxx-xx
ga_domain: wghglory.github.io

# Sidebar settings
sidebar-about-description: A very lame cool person #光辉岁月 # 个人描述
sidebar-avatar: /images/avatar.jpg    # use absolute URL


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value

# friends
# friends: [
# 	{
#         title: "your friend title",
#         href: "your fiend path"
# 	},
# 	{
#         title: "your friend title 2",
#         href: "your friend path 2"
# 	}
# ]


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://wghglory.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true #true:在建立文件时，Hexo会自动建立一个与文章同名的文件夹，可以把与该文章相关的所有资源都放到那个文件夹
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:


# Category & Tag
default_category: uncategorized
category_map:
    编程: programming
    作品: myworks
    生活: life
    其他: other
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/wghglory/wghglory.github.io.git
  branch: master

# Extensions
Plugins:
- hexo-generator-feed
- hexo-generator-sitemap

#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20

#sitemap
sitemap:
  path: sitemap.xml

# img CDN path
cdn-url:  # 你的CDN地址

# Qiniu imageView2 API
# More info http://developer.qiniu.com/code/v6/api/kodo-api/image/imageview2.html
clip-content: "?imageView2/1/w/1400/h/400/interlace/1/q/90"
clip-avatar: "?imageView2/2/w/300/h/300/interlace/1/q/90"
clip-home-post-bg: "?imageView2/1/w/800/h/300/interlace/1/q/70"

# post default images, when viewing the post detail, picture on the top
post-default-img: /images/default-post.jpg
post-default-img-mobile: /images/default-post.jpg #移动端显示的图片

tag-img: /images/tag.jpg

# search api , set your custom key
#swiftype_key:

# add post views
leancloud_visitors:
  enable: true
  app_id: E6rF07nXwdjW2bqLM59LERB4-gzGzoHsz
  app_key: SpkVez7QIOXIDXh5iqoMt338
